apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-${ENV_NAME}
  namespace: ${NAMESPACE}
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: ${REPLICA_COUNT} # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ot-emp-ui/dev/dev2:${IMAGE_TAG}
        ports:
        - containerPort: 80
