name: Test exiting on failure

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: [ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: Try to fail
      run: exit 1
    - name: Print message if we don't fail
      run: echo Should not get here

  publish:
    needs: build
    runs-on: [ubuntu-latest]

    steps:
    - name: Print message if we don't fail
      run: echo Should not get here
